use_frameworks!

source 'https://gitee.com/differentialmanifold/cocoa-pods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

target 'Example-private-repo' do
  pod 'MyLibrary', '0.2.0'
end
